version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: on_tap_khoa_hoc
      MYSQL_USER: lamnt2010
      MYSQL_PASSWORD: lamnt2010
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mysql://lamnt2010:lamnt2010@mysql:3306/on_tap_khoa_hoc
      - PORT=3306
      - MYSQL_HOST=mysql
      - MYSQL_USER=lamnt2010
      - MYSQL_PASSWORD=lamnt2010
      - MYSQL_DATABASE=on_tap_khoa_hoc                    
      - SECRET_KEY=REDACTED
      - REFRESH_SECRET_KEY=REDACTED
    depends_on:
      mysql:
        condition: service_healthy
  
  frontend:
    build:
      context: ./client

    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
