version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
  
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
